# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 13:25
from django.db import migrations, models

from wagtail.images.utils import get_fill_filter_spec_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0014_add_filter_spec_field'),
    ]

    forward, reverse = get_fill_filter_spec_migrations('wagtailimages', 'Rendition')
    forward2, reverse2 = get_fill_filter_spec_migrations('wagtailimages', 'UserRendition')
    operations = [
        migrations.RunPython(forward, reverse),
        migrations.RunPython(forward2, reverse2),
        migrations.AlterField(
            model_name='rendition',
            name='filter_spec',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userrendition',
            name='filter_spec',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
