# Generated by Django 2.0.10 on 2019-03-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrendition',
            name='alt_text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
