# Generated by Django 2.0.13 on 2019-03-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_userrendition_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendition',
            name='alt_text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
