# Generated by Django 2.2.12 on 2020-04-15 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('wagtailimages', '0022_auto_20190506_2114'),
    ]

    operations = [
    ]
