# Generated by Django 2.2.12 on 2020-04-15 06:44

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0043_customdocument_fancy_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customimage',
            name='show_in_catalogue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customimagefilepath',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customimagefilepath',
            name='show_in_catalogue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customrendition',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customimage',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='To enter multi-word tags, use double quotes: "some tag".', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='customimagefilepath',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='To enter multi-word tags, use double quotes: "some tag".', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags'),
        ),
    ]
