# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-11 17:04
from __future__ import unicode_literals

from django.db import migrations, models


def remove_duplicate_user_renditions(apps, schema_editor):
    Rendition = apps.get_model('wagtailimages.UserRendition')

    # Find all filter_spec / image_id pairings that appear multiple
    # times in the renditions table with focal_point_key = NULL
    duplicates = (
        Rendition.objects.all().
        values('image_id', 'filter_spec').
        annotate(count_id=models.Count('id'), min_id=models.Min('id')).
        filter(count_id__gt=1)
    )

    # Delete all occurrences of those pairings, except for the one

    for duplicate in duplicates:
        Rendition.objects.filter(
            image=duplicate['image_id'],
            filter_spec=duplicate['filter_spec']
        ).exclude(
            id=duplicate['min_id']
        ).delete()


def reverse_remove_duplicate_user_renditions(*args, **kwargs):
    """This is a no-op. The migration removes duplicates, we cannot recreate those duplicates."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0015_fill_filter_spec_field'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_user_renditions,
                             reverse_remove_duplicate_user_renditions),
    ]
