# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailimages.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0015_fill_filter_spec_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrendition',
            name='file',
            field=models.ImageField(height_field='height', upload_to=wagtail.wagtailimages.models.get_rendition_upload_to, width_field='width'),
        ),
    ]
