# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_page_archived'),
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
    ]

    operations = [
    ]
