# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0031_merge_20161127_2048'),
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
    ]

    operations = [
    ]
