# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailcore', '0034_merge_20180224_1945'),
    ]

    operations = [
    ]
