# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='private_title',
            field=models.CharField(blank=True, help_text='Title for internal use.', max_length=200, null=True, verbose_name='private title'),
        ),
    ]
