# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('wagtailcore', '0032_merge_20161127_2156'),
    ]

    operations = [
    ]
