# Generated by Django 2.2.7 on 2019-11-29 10:46
# Wagtail upgrade notes:
# Original dependency was 0041_group_collection_permissions_verbose_name_plural
# TODO: Always check migrations from this point onward to make sure there is no unwanted DB change

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0043_merge_20200415_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagerevision',
            name='approved_go_live_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='approved go live at'),
        ),
    ]
