# Generated by Django 2.2.12 on 2020-04-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailcore', '0042_add_preview_page_permission'),
    ]

    operations = [
    ]
